CREATE TABLE nutzer (
    id uuid PRIMARY KEY,
    username VARCHAR(50) NOT NULL unique,
    email VARCHAR(50) NOT NULL unique,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE buch
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    isbn VARCHAR(13),
    titel VARCHAR(100),
    autor VARCHAR(100),
    coverbild VARCHAR(100),
    tid VARCHAR(15)
-- Verfügbarkeit?
);

ALTER TABLE buch
    ADD CONSTRAINT fk_buch_nutzer
        FOREIGN KEY (nutzer_id)
            REFERENCES nutzer (id);



