CREATE TABLE nutzer
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nutzername VARCHAR(50) NOT NULL,
    passwort VARCHAR(50) NOT NULL,
);

CREATE TABLE buch
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    isbn INTEGER,
    titel VARCHAR(100),
    autor VARCHAR(100),
    coverbild VARCHAR(100)
-- Verfügbarkeit?
);

ALTER TABLE buch
    ADD CONSTRAINT fk_buch_nutzer
        FOREIGN KEY (nutzer_id)
            REFERENCES nutzer (id);



