CREATE TABLE nutzer (
    id uuid PRIMARY KEY,
    username VARCHAR(50) NOT NULL unique,
    email VARCHAR(50) NOT NULL unique,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE buch
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    isbn VARCHAR(13),
    title VARCHAR(100),
    author VARCHAR(100),
    coverbild TEXT,
    tid VARCHAR(15)
-- Verfügbarkeit?
);

/*
ALTER TABLE buch
    ADD CONSTRAINT fk_buch_nutzer
        FOREIGN KEY (nutzer_id)
            REFERENCES nutzer (id);

*/

ALTER TABLE buch
    ADD COLUMN user_id uuid;

ALTER TABLE buch
    ADD CONSTRAINT fk_nutzer_book
        FOREIGN KEY (user_id)
            REFERENCES nutzer(id);