CREATE TABLE zitate
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50),
    zitat VARCHAR(250)
);

ALTER SEQUENCE buch_id_seq RESTART WITH 1;

INSERT INTO zitate (name,zitat) VALUES ('Albert Einstein','Das einzige, was Sie unbedingt wissen müssen, ist der Standort einer Bibliothek.');
INSERT INTO zitate (name,zitat) VALUES ('Aldous Huxley','Wer zu lesen versteht, besitzt den Schlüssel zu großen Taten, zu unerträumten Möglichkeiten.');
INSERT INTO zitate (name,zitat) VALUES ('Aphra Behn','…diese vollkommene Ruhe des Lebens, die nirgendwo anders zu finden ist, als in einem Rückzugsort, einem treuen Freund und einer gute Bibliothek…');
INSERT INTO zitate (name,zitat) VALUES ('Augustinus Aurelius','Die Welt ist ein Buch. Wer nie reist, sieht nur eine Seite davon.');
INSERT INTO zitate (name,zitat) VALUES ('Bertha von Suttner','Es ist erstaunlich, wie sehr man ein solches Buch als Freund empfindet - wie man ihm alles sagen und klagen kann, wie man über seine Blätter die Tränen weinen kann, die man den anderen, besonders einem geliebten Kranken, verbergen muss.');
INSERT INTO zitate (name,zitat) VALUES ('Bertolt Brecht','Hungriger, greif nach dem Buch: Es ist eine Waffe!');
INSERT INTO zitate (name,zitat) VALUES ('Blaise Pascal','Die besten Bücher sind die, von denen jeder Leser meint, er hätte sie selbst machen können.');
INSERT INTO zitate (name,zitat) VALUES ('Carl Peter Fröhling','Ein Leben ohne Bücher ist wie eine Kindheit ohne Märchen, ist wie eine Jugend ohne Liebe, ist wie ein Alter ohne Frieden.');
INSERT INTO zitate (name,zitat) VALUES ('Christian Morgenstern','Über jedem guten Buch muss das Gesicht des Lesers von Zeit zu Zeit hell werden.');
INSERT INTO zitate (name,zitat) VALUES ('Cicero','Ein Raum ohne Bücher ist ein Körper ohne Seele.');
INSERT INTO zitate (name,zitat) VALUES ('Cornelia Funke','Nichts verscheuchte böse Träume schneller als das Rascheln von bedrucktem Papier.');
INSERT INTO zitate (name,zitat) VALUES ('Erasmus von Rotterdam','Der Umgang mit Büchern bringt die Leute um den Verstand.');
INSERT INTO zitate (name,zitat) VALUES ('Ernst Ferstl','Wenn die Liebe ein Medikament wäre – der Beipackzettel wäre ein dickes Buch.');
INSERT INTO zitate (name,zitat) VALUES ('Ernst Reinhold Hauschka','Nicht wer Zeit hat, liest Bücher, sondern wer Lust hat, Bücher zu lesen, der liest, ob er viel Zeit hat oder wenig.');
INSERT INTO zitate (name,zitat) VALUES ('Fernando Pessoa','Lesen heißt durch fremde Hand träumen.');
INSERT INTO zitate (name,zitat) VALUES ('Francis Bacon','Bücher sind Schiffe, welche die weiten Meere der Zeit durcheilen.');
INSERT INTO zitate (name,zitat) VALUES ('Francis Bacon','Einige Bücher soll man kosten, andere verschlingen, und einige wenige kauen und verdauen.');
INSERT INTO zitate (name,zitat) VALUES ('Franz Kafka','Ein Buch muss die Axt sein für das gefrorene Meer in uns.');
INSERT INTO zitate (name,zitat) VALUES ('George R. R. Martin','Ein Verstand braucht Bücher, wie ein Schwert den Schleifstein.');
INSERT INTO zitate (name,zitat) VALUES ('Gotthold Ephraim Lessing','Die Welt allein bildet einen vollkommenen Menschen nicht. Das Lesen der besten Schriftsteller muss dazu kommen.');
INSERT INTO zitate (name,zitat) VALUES ('Groucho Marx','Fernsehen bildet. Immer, wenn der Fernseher an ist, gehe ich in ein anderes Zimmer und lese.');
INSERT INTO zitate (name,zitat) VALUES ('Gustave Flaubert','Lies, um zu leben.');
INSERT INTO zitate (name,zitat) VALUES ('Heinrich Heine','Von allen Welten, die der Mensch erschaffen hat, ist die der Bücher die Gewaltigste.');
INSERT INTO zitate (name,zitat) VALUES ('Heinrich Laube','Bücher sind nicht Denkmäler der Vergangenheit, sondern Waffe der Gegenwart.');
INSERT INTO zitate (name,zitat) VALUES ('Helen Hayes','Von seinen Eltern lernt man lieben, lachen, und laufen. Doch erst wenn man mit Büchern in Berührung kommt, entdeckt man, dass man Flügel hat.');
INSERT INTO zitate (name,zitat) VALUES ('James Daniel','Bücher sind fliegende Teppiche ins Reich der Phantasie.');
INSERT INTO zitate (name,zitat) VALUES ('James Russell Lowell','Bücher sind Bienen, die lebenzeugenden Blütenstaub von einem Geist zum andern tragen.');
INSERT INTO zitate (name,zitat) VALUES ('Jean Paul','Bücher lesen heißt, wandern gehen in ferne Welten, aus den Stuben, über die Sterne.');
INSERT INTO zitate (name,zitat) VALUES ('Johann Wolfgang von Goethe','In Bibliotheken fühlt man sich wie in der Gegenwart eines großen Kapitals, das geräuschlos unberechenbare Zinsen spendet.');
INSERT INTO zitate (name,zitat) VALUES ('Johann Wolfgang von Goethe','Es ist ein großer Unterschied, ob ich lese zum Genuss und Belebung oder zur Erkenntnis und Belehrung.');
INSERT INTO zitate (name,zitat) VALUES ('Johann Wolfgang von Goethe','Wer Bücher liest, schaut in die Welt und nicht nur bis zum Zaune.');
INSERT INTO zitate (name,zitat) VALUES ('Jorge Luis Borges','Ich habe mir das Paradies immer als eine Art Bibliothek vorgestellt.');
INSERT INTO zitate (name,zitat) VALUES ('Kai Meyer','Während sie die Stufen zur Bibliothek hinablief, konnte Furia die Geschichten schon riechen: den besten Geruch der Welt.');
INSERT INTO zitate (name,zitat) VALUES ('Kathleen Norris','Zu wissen, dass am Ende eines langen Tages ein gutes Buch auf einen wartet, macht den Tag fröhlicher.');
INSERT INTO zitate (name,zitat) VALUES ('Kurt Tucholsky','Im Bett soll man nur leichte und unterhaltene Lektüre zu sich nehmen, sowie spannende und beruhigende, ferner ganz schwere, wissenschaftliche und frivole sowie mittelschwere und jede sonstige, andere Arten aber nicht.');
INSERT INTO zitate (name,zitat) VALUES ('Lao-Tse','Ein schönes Buch ist wie ein Schmetterling. Leicht liegt es in der Hand, entführt uns von einer Blüte zur nächsten und lässt den Himmel ahnen.');
INSERT INTO zitate (name,zitat) VALUES ('Lew Nikolajewitsch Tolstoi','Beim Lesen lässt sich vortrefflich denken.');
INSERT INTO zitate (name,zitat) VALUES ('Malcolm Stevenson Forbes','Feder und Papier entzünden mehr Feuer als alle Streichhölzer der Welt.');
INSERT INTO zitate (name,zitat) VALUES ('Marcus Tullius Cicero','Wenn du einen Garten und eine Bibliothek hast, wird es dir an nichts fehlen.');
INSERT INTO zitate (name,zitat) VALUES ('Marguerite Duras','Ein Buch lesen – für mich ist das das Erforschen eines Universums.');
INSERT INTO zitate (name,zitat) VALUES ('Marie von Ebner-Eschenbach','In einem guten Buche stehen mehr Wahrheiten, als sein Verfasser hineinzuschreiben meinte.');
INSERT INTO zitate (name,zitat) VALUES ('Marie-Henri Beyle','Ein Roman ist wie der Bogen einer Geige und ihr Resonanzkörper wie die Seele des Lesers.');
INSERT INTO zitate (name,zitat) VALUES ('Martin Walser','Ein Buch ist für mich eine Art Schaufel, mit der ich mich umgrabe.');
INSERT INTO zitate (name,zitat) VALUES ('Maxim Gorki','Je mehr ich las, umso näher brachten die Bücher mir die Welt, um so heller und bedeutsamer wurde für mich das Leben.');
INSERT INTO zitate (name,zitat) VALUES ('Mosche Ibn Esra','Bücher sind die Hüllen der Weisheit, bestickt mit den Perlen der Worte.');
INSERT INTO zitate (name,zitat) VALUES ('Oscar Wilde','Die Literatur greift immer dem Leben vor. Sie ahmt das Leben nicht nach, sondern formt es nach ihrer Absicht.');
INSERT INTO zitate (name,zitat) VALUES ('Ray Bradbury','Ohne die Bibliothek gibt es keine Zivilisation.');
INSERT INTO zitate (name,zitat) VALUES ('Rose Macaulay','Nur eines ist vergnüglicher als abends im Bett, vor dem Einschlafen, noch ein Buch zu lesen – und das ist morgens, statt aufzustehen, noch ein Stündchen im Bett zu lesen.');
INSERT INTO zitate (name,zitat) VALUES ('Stephen King','Wenn alles andere fehlschlägt, kündigen Sie und gehen Sie in die Bibliothek.');
INSERT INTO zitate (name,zitat) VALUES ('Susan Sontag','Meine Bibliothek ist ein Archiv der Sehnsüchte.');
INSERT INTO zitate (name,zitat) VALUES ('Thomas Carlyle','In Büchern liegt die Seele aller gewesenen Zeit.');
INSERT INTO zitate (name,zitat) VALUES ('Voltaire','Lesen stärkt die Seele');
INSERT INTO zitate (name,zitat) VALUES ('Walt Disney','Es gibt mehr Schätze in Büchern als Piratenbeute auf der Schatzinsel… und das Beste ist, du kannst diesen Reichtum jeden Tag deines Lebens genießen.');
