ALTER SEQUENCE standort_id_seq RESTART WITH 1;

INSERT INTO standort(name)
VALUES ('Alstertal'),
       ('Altona'),
       ('Barmbek'),
       ('Bergedorf'),
       ('Billstedt'),
       ('Bramfeld'),
       ('Dehnhaide'),
       ('Eidelstedt'),
       ('Eimsbüttel'),
       ('Elbvororte'),
       ('Farmsen'),
       ('Finkenwerder'),
       ('Fuhlsbüttel'),
       ('Harburg'),
       ('Holstenstraße'),
       ('Horn'),
       ('Jenfelder Au'),
       ('Kirchdorf'),
       ('Langenhorn'),
       ('Lokstedt'),
       ('Mümmelmannsberg'),
       ('Neuallermöhe'),
       ('Neugraben'),
       ('Niendorf'),
       ('Osdorfer Born'),
       ('Rahlstedt'),
       ('Schnelsen'),
       ('Steilshoop'),
       ('Volksdorf'),
       ('Wandsbek'),
       ('Wilhelmsburg'),
       ('Winterhude'),
       ('Zentralbibliothek');